# Generated by Django 5.2.3 on 2025-07-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card_profilecard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilecard',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='profilecard',
            unique_together={('profile', 'card')},
        ),
    ]
