# Generated by Django 5.2.3 on 2025-07-25 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_collectioncategory_card_price_to_unlock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('common', 'Commun'), ('rare', 'Rare'), ('epic', 'Légendaire')], default='common', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='collectioncategory',
            name='name',
            field=models.CharField(choices=[('composer', 'Compositeur'), ('instrument', 'Instrument')], default='composer', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cardrarity'),
        ),
    ]
