# Generated by Django 5.2.3 on 2025-07-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cardrarity_alter_collectioncategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
