# Generated by Django 5.2.3 on 2025-08-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lesson_completedlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_streak_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
