# Generated by Django 5.2.3 on 2025-08-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_last_streak_date_profile_streak_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedlesson',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
    ]
