# Generated by Django 5.2.3 on 2025-08-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_completedlesson_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedlesson',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
