# Generated by Django 5.2.3 on 2026-01-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notename_musicnote_scrollinggamelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_scrolling_game_level',
            field=models.IntegerField(default=1),
        ),
    ]
