# Generated by Django 5.2.3 on 2026-02-09 17:10
# Modified for MySQL compatibility: disable FK checks during table drops

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_current_scrolling_game_level'),
    ]

    operations = [
        # Disable FK checks so MySQL lets us drop tables with FK dependencies
        migrations.RunSQL(
            sql='SET FOREIGN_KEY_CHECKS = 0;',
            reverse_sql='SET FOREIGN_KEY_CHECKS = 1;',
        ),
        migrations.AlterUniqueTogether(
            name='profilecard',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='ProfileCard',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='CardRarity',
        ),
        migrations.DeleteModel(
            name='CollectionCategory',
        ),
        migrations.RunSQL(
            sql='SET FOREIGN_KEY_CHECKS = 1;',
            reverse_sql='SET FOREIGN_KEY_CHECKS = 0;',
        ),
    ]
