# Generated by Django 5.2.3 on 2026-02-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_current_scrolling_game_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilecard',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='CollectionCategory',
        ),
        migrations.DeleteModel(
            name='CardRarity',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='ProfileCard',
        ),
    ]
