# Generated by Django 5.2.3 on 2026-02-09 17:10
# Modified for MySQL compatibility: AlterUniqueTogether causes a duplicate index error
# on MySQL because it tries to create a FK index that already exists.
# We skip the DB-level AlterUniqueTogether and drop everything via raw SQL instead.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_current_scrolling_game_level'),
    ]

    operations = [
        # Tell Django's state machine that unique_together is gone,
        # but do nothing in the actual database (we'll drop the table below).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='profilecard',
                    unique_together=None,
                ),
            ],
            database_operations=[],
        ),
        migrations.RunSQL(
            sql="""
                SET FOREIGN_KEY_CHECKS = 0;
                DROP TABLE IF EXISTS core_profilecard;
                DROP TABLE IF EXISTS core_card;
                DROP TABLE IF EXISTS core_cardrarity;
                DROP TABLE IF EXISTS core_collectioncategory;
                SET FOREIGN_KEY_CHECKS = 1;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Keep the state in sync: tell Django these models are deleted.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='ProfileCard'),
                migrations.DeleteModel(name='Card'),
                migrations.DeleteModel(name='CardRarity'),
                migrations.DeleteModel(name='CollectionCategory'),
            ],
            database_operations=[],
        ),
    ]
