# Generated by Django 5.2.3 on 2026-02-09 19:29
# Modified for MySQL compatibility: same AlterUniqueTogether + duplicate index issue.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_card_category_remove_card_rarity_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='completedlesson',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='completedlesson',
                    name='lesson',
                ),
                migrations.RemoveField(
                    model_name='completedlesson',
                    name='profile',
                ),
            ],
            database_operations=[],
        ),
        migrations.RunSQL(
            sql="""
                SET FOREIGN_KEY_CHECKS = 0;
                DROP TABLE IF EXISTS core_completedlesson;
                DROP TABLE IF EXISTS core_lesson;
                SET FOREIGN_KEY_CHECKS = 1;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='Lesson'),
                migrations.DeleteModel(name='CompletedLesson'),
            ],
            database_operations=[],
        ),
    ]
