# Generated by Django 5.2.3 on 2026-02-09 19:29
# Modified for MySQL compatibility: disable FK checks during table drops

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_card_category_remove_card_rarity_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='SET FOREIGN_KEY_CHECKS = 0;',
            reverse_sql='SET FOREIGN_KEY_CHECKS = 1;',
        ),
        migrations.AlterUniqueTogether(
            name='completedlesson',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='completedlesson',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='completedlesson',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='CompletedLesson',
        ),
        migrations.RunSQL(
            sql='SET FOREIGN_KEY_CHECKS = 1;',
            reverse_sql='SET FOREIGN_KEY_CHECKS = 0;',
        ),
    ]
