# Generated by Django 5.2.3 on 2026-02-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_completedlesson_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrollinggamelevel',
            name='notes',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='InstrumentCategory',
        ),
        migrations.DeleteModel(
            name='ScrollingGameLevel',
        ),
    ]
