# Generated by Django 5.2.3 on 2026-02-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_scrollinggamelevel_notes_delete_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nb_correct_answers_srolling_game',
            field=models.IntegerField(default=0),
        ),
    ]
