# Generated by Django 5.2.3 on 2026-05-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_seed_quests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='quest_type',
            field=models.CharField(choices=[('read_lesson', 'Lire des cours'), ('play_notes_reading', 'Jouer à Lecture de notes'), ('learn_lyrics', 'Apprendre des paroles')], max_length=40),
        ),
    ]
