# Generated by Django 5.2.3 on 2026-05-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='activity_type',
            field=models.CharField(choices=[('lesson', 'Cours'), ('notes_reading', 'Lecture de notes'), ('blind_test', 'Blind test'), ('scales_builder', 'Construction de gammes'), ('lyrics_game', 'Paroles de chanson')], max_length=30),
        ),
    ]
