# Generated by Django 5.2.3 on 2026-05-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyricsprogress',
            name='lines_unlocked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
