# Generated by Django 5.2.3 on 2025-09-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('secondary_title', models.CharField(max_length=255)),
                ('composer', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.IntegerField(default=1)),
                ('file', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
