# Generated by Django 5.2.3 on 2025-09-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_track_secondary_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='file',
        ),
        migrations.AddField(
            model_name='track',
            name='filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
