# Generated by Django 5.2.3 on 2026-04-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gameprogress_scrollinggame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrollingGameLevel',
        ),
    ]
