# Generated by Django 5.2.3 on 2026-04-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_scrollinggamelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrollinggame',
            name='current_level_bass',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scrollinggame',
            name='nb_correct_answers_bass',
            field=models.IntegerField(default=0),
        ),
    ]
