# Generated by Django 5.2.3 on 2026-06-27 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_profile_nb_correct_answers_srolling_game'),
        ('games', '0007_add_bass_clef_to_scrolling_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprogress',
            name='current_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='game_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_progressions', to='core.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='gameprogress',
            unique_together={('profile', 'game_type')},
        ),
    ]
