# Generated by Django 5.2.3 on 2026-06-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_gameprogress_current_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrollingGame',
        ),
    ]
