# Generated by Django 5.2.3 on 2026-06-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_delete_scrollinggame'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='image_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
