# Generated by Django 5.2.3 on 2026-02-09 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_remove_card_category_remove_card_rarity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('common', 'Commun'), ('rare', 'Rare'), ('epic', 'Légendaire')], default='common', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('composer', 'Compositeur'), ('instrument', 'Instrument')], default='composer', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_to_unlock', models.IntegerField(default=5)),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardrarity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.collectioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_cards', to='cards.card')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_cards', to='core.profile')),
            ],
            options={
                'unique_together': {('profile', 'card')},
            },
        ),
    ]
